version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - microservices-network

  comment-service:
    build: ./comment-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./comment-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - microservices-network

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - microservices-network

  project-service:
    build: ./project-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
    volumes:
      - ./project-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - microservices-network

  tasks-service:
    build: ./tasks-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
    volumes:
      - ./tasks-service:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - microservices-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - comment-service
      - notification-service
      - project-service
      - tasks-service
    networks:
      - microservices-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

volumes:
  mongodb_data:

networks:
  microservices-network:
    driver: bridge